spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/demo   #    url при локальной версии: jdbc:postgresql://localhost:5432/demo
    driver-class-name: org.postgresql.Driver
    username: demo
    password: demo
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

modbus:
  devices:
    # Если указать только часть параметров - остальные возьмутся из значений по умолчанию:
    # port=502, rateMs=2000, timeoutMs=1000, retries=1, registers=[]
    - name: device1
      ip: host.docker.internal
      port: 502
      unitId: 1
      rateMs: 5000
      timeoutMs: 1000
      retries: 1
      registers: [0,1,2,3]
    - name: device2
      ip: host.docker.internal
      port: 502
      unitId: 2
      rateMs: 5000
      timeoutMs: 1000
      retries: 1
      registers: [0,1,2,3]

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true

logging:
  level:
    root: WARN
    org.hibernate.SQL: OFF
    com.example.demo.service.DevicePollingService: WARN
