spring:
  datasource:
    url: jdbc:h2:mem:demo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

modbus:
  devices:
    - name: dev1
      ip: host.docker.internal
      port: 502
      unitId: 1
      rateMs: 5000
      timeoutMs: 1000
      retries: 1
      registers: [0,1,2,3]
    - name: dev2
      ip: host.docker.internal
      port: 502
      unitId: 2
      rateMs: 5000
      timeoutMs: 1000
      retries: 1
      registers: [0,1,2,3]

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true

logging:
  level:
    root: INFO
    com.example.demo: DEBUG
